/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Вернуть предстоящие бронирования по всем типам событий, отсортированные по startAt по возрастанию. */
        get: operations["AdminBookings_listUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Вернуть типы событий, видимые владельцу в админской части. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Создать тип события. Редактирование и удаление типов событий не входят в этот контракт. */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование гостя для выбранного слота.
         *
         *     Сервер рассчитывает endAt из длительности выбранного типа события и проверяет,
         *     что запрошенный startAt относится к сгенерированному свободному слоту.
         *     Возвращает 409, если интервал конфликтует с существующим бронированием.
         *     Возвращает 422, если слот находится вне 14-дневного окна, вне доступности
         *     09:00-18:00 или не совпадает с шагом сетки для типа события.
         */
        post: operations["PublicBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Вернуть типы событий, доступные гостям. */
        get: operations["PublicEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Вернуть свободные слоты для выбранного типа события.
         *
         *     Слоты рассчитываются на ближайшие 14 дней от текущей даты, в интервале
         *     с 09:00 до 18:00 по локальному времени приложения. Шаг сетки слотов равен
         *     длительности типа события. Уже забронированные интервалы исключаются по всем
         *     типам событий.
         */
        get: operations["PublicSlots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование гостя для выбранного типа события и слота. */
        Booking: {
            /** @description Стабильный идентификатор бронирования. */
            id: string;
            /** @description Забронированный тип события. */
            eventType: components["schemas"]["EventType"];
            /** @description Отображаемое имя гостя. */
            guestName: string;
            /** @description Электронная почта гостя, которая используется как контакт в списке встреч владельца. */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Дата и время начала бронирования.
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Дата и время окончания бронирования, рассчитанные из startAt и eventType.durationMinutes.
             */
            endAt: string;
            /**
             * Format: date-time
             * @description Дата и время создания бронирования.
             */
            createdAt: string;
        };
        /** @description Запрошенный слот конфликтует с существующим бронированием. */
        ConflictError: {
            /** @enum {string} */
            code: "BOOKING_CONFLICT";
            message: string;
        };
        /** @description Данные, которые гость передает при создании бронирования. */
        CreateBookingRequest: {
            /** @description Идентификатор выбранного типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Дата и время начала выбранного слота.
             */
            startAt: string;
            /** @description Отображаемое имя гостя. */
            guestName: string;
            /** @description Электронная почта гостя. */
            guestEmail: string;
        };
        /** @description Данные, которые владелец передает при создании типа события. */
        CreateEventTypeRequest: {
            /** @description Публичное название типа события. */
            title: string;
            /** @description Публичное описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. Это значение также определяет шаг генерируемых слотов.
             */
            durationMinutes: number;
        };
        /** @description Стандартный ответ API с ошибкой. */
        ErrorResponse: {
            /** @description Машиночитаемый код ошибки. */
            code: string;
            /** @description Человекочитаемое сообщение об ошибке. */
            message: string;
        };
        /** @description Тип встречи, который гость может забронировать. */
        EventType: {
            /** @description Стабильный идентификатор типа события. */
            id: string;
            /** @description Публичное название типа события. */
            title: string;
            /** @description Публичное описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. Это значение также определяет шаг генерируемых слотов.
             */
            durationMinutes: number;
        };
        /** @description Тип события не существует. */
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /** @description Заранее заданный профиль владельца календаря. Профиль есть в домене, но не управляется через API. */
        Owner: {
            /** @description Стабильный идентификатор владельца. */
            id: string;
            /** @description Отображаемое имя владельца на страницах календаря. */
            name: string;
            /** @description Часовой пояс владельца, который используется для отображения и расчета локальной доступности. */
            timezone: string;
        };
        /** @description Вычисленный свободный временной интервал для выбранного типа события. */
        Slot: {
            /** @description Тип события, для которого рассчитан этот слот. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Дата и время начала слота.
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Дата и время окончания слота. Значение равно startAt плюс длительность типа события.
             */
            endAt: string;
            /**
             * Format: int32
             * @description Длительность, скопированная из выбранного типа события.
             */
            durationMinutes: number;
        };
        /** @description Запрос нарушает правила входных данных или бизнес-валидации. */
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_listUpcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "book-1",
                     *         "eventType": {
                     *           "id": "evt-15",
                     *           "title": "Встреча 15 минут",
                     *           "description": "Короткий тип события для быстрого слота.",
                     *           "durationMinutes": 15
                     *         },
                     *         "guestName": "Иван Петров",
                     *         "guestEmail": "ivan@example.com",
                     *         "startAt": "2026-06-04T09:00:00Z",
                     *         "endAt": "2026-06-04T09:15:00Z",
                     *         "createdAt": "2026-06-03T08:30:00Z"
                     *       },
                     *       {
                     *         "id": "book-2",
                     *         "eventType": {
                     *           "id": "evt-30",
                     *           "title": "Встреча 30 минут",
                     *           "description": "Базовый тип события для бронирования.",
                     *           "durationMinutes": 30
                     *         },
                     *         "guestName": "Мария Смирнова",
                     *         "guestEmail": "maria@example.com",
                     *         "startAt": "2026-06-05T12:00:00Z",
                     *         "endAt": "2026-06-05T12:30:00Z",
                     *         "createdAt": "2026-06-03T09:10:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "evt-15",
                     *         "title": "Встреча 15 минут",
                     *         "description": "Короткий тип события для быстрого слота.",
                     *         "durationMinutes": 15
                     *       },
                     *       {
                     *         "id": "evt-30",
                     *         "title": "Встреча 30 минут",
                     *         "description": "Базовый тип события для бронирования.",
                     *         "durationMinutes": 30
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Встреча 45 минут",
                 *       "description": "Расширенный слот для подробного разговора.",
                 *       "durationMinutes": 45
                 *     }
                 */
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "evt-45",
                     *       "title": "Встреча 45 минут",
                     *       "description": "Расширенный слот для подробного разговора.",
                     *       "durationMinutes": 45
                     *     }
                     */
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicBookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "eventTypeId": "evt-15",
                 *       "startAt": "2026-06-04T09:45:00Z",
                 *       "guestName": "Алексей Иванов",
                 *       "guestEmail": "alexey@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "book-3",
                     *       "eventType": {
                     *         "id": "evt-15",
                     *         "title": "Встреча 15 минут",
                     *         "description": "Короткий тип события для быстрого слота.",
                     *         "durationMinutes": 15
                     *       },
                     *       "guestName": "Алексей Иванов",
                     *       "guestEmail": "alexey@example.com",
                     *       "startAt": "2026-06-04T09:45:00Z",
                     *       "endAt": "2026-06-04T10:00:00Z",
                     *       "createdAt": "2026-06-03T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "evt-15",
                     *         "title": "Встреча 15 минут",
                     *         "description": "Короткий тип события для быстрого слота.",
                     *         "durationMinutes": 15
                     *       },
                     *       {
                     *         "id": "evt-30",
                     *         "title": "Встреча 30 минут",
                     *         "description": "Базовый тип события для бронирования.",
                     *         "durationMinutes": 30
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    PublicSlots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "eventTypeId": "evt-15",
                     *         "startAt": "2026-06-04T09:45:00Z",
                     *         "endAt": "2026-06-04T10:00:00Z",
                     *         "durationMinutes": 15
                     *       },
                     *       {
                     *         "eventTypeId": "evt-15",
                     *         "startAt": "2026-06-04T10:00:00Z",
                     *         "endAt": "2026-06-04T10:15:00Z",
                     *         "durationMinutes": 15
                     *       },
                     *       {
                     *         "eventTypeId": "evt-15",
                     *         "startAt": "2026-06-05T11:15:00Z",
                     *         "endAt": "2026-06-05T11:30:00Z",
                     *         "durationMinutes": 15
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
